---
title: "Prospectus Overview"
author: "Danton Noriega"
date: '`r format(Sys.time(), "%B %d, %Y")`'
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
rfiles <- list.files("R")
invisible(sapply(file.path("R", rfiles), source))
```

class: middle



# At a Glance

### **Chapter 1** <br/>An Analysis of the Double Up Food Bucks Program
### **Chapter 2** <br/>SNAP EBT Transfer Dates & Off-Cycle Demand for Formal Assistance
### **Chapter 3** <br/>The Durham Connects Pilot & Requests for Social Services


---
class: center, middle, inverse

# Chapter 1

## Double Up Food Bucks 

---

### Research Question

> How effective is the DUFB financial incentive at increasing the fresh fruits and vegetables purchased by SNAP shoppers within a grocery store environment?

--

### Hypotheses

- A slight increase (1 - 2%) in SNAP EBT expenditures on fruits and vegetables (FVs) during the months the DUFB incentive is active in the experimental stores (Aug - Dec). 
- No significant differences in FV expenditures during the months the incentive is not in effect (Jan - July).
- The state's SNAP benefit schedule will affect when differences are detected. Difference, if found, will be detected during the 1st, 2nd, and 3rd weeks, fading during the 4th week.

---
# Quick Background

### Double Up Food Bucks (DUFB)

- Financial incentive program targetting SNAP beneficiaries
- Doubles purchasing power for FVs up to $20/day
- Initially started in farmer's markets but expanding to other retail environments

--

### Fair Food Network (FFN) and FINI

- Started Double Up Food Bucks in 2009
  - One of many organization promoting financial incentive programs
- Lead lobbying effort for the Food Insecurity Nutrition Initiative (FINI)
- FINI provided $100 million to fund numerous pilot programs
  - $5.17 million was awarded to FFN to help expand and test adjustments to DUFB

---

# Policy Motivation

### Problem

- High consumption of unhealthy foods, low consumption of fruits and vegetables
- Overtime, poor diet leads to adverse health outcomes
- Chronic diet-related diseases are expensive
- US government could save lives and money by improving diets

---

### Supplemental Nutrition Assistance Program (SNAP)

- Anti-hunger program, not a nutrition program
- Currently, few restrictions on what can be purchased with SNAP benefits
- However, government funds SNAP, Medicare, and Medicaid
- These programs are expensive
    - SNAP — $74 billion FY2015
    - Medicare — $646.2 billion FY2015
    - Medicaid - $545.1 billion FY2015
- Substantial overlap between families participating in SNAP and Medicaid/Medicare

**It is therefore possible to save money by improving the diet of SNAP beneficiaries.**

---

# Proposed Policy Solutions

### Restrict SNAP

Make SNAP more like Woman, Infants, and Children.

- WIC strictly defines what beneficiaries *can* buy
- SNAP defines what beneficiaries *cannot* buy

--

### Financial Incentives

Increase fruit and vegetable purchases using financial incentives.

- Includes DUFB and DUFB-like programs currently being evaluated
- Also includes Healthy Incentives Pilot (HIP)
  - Piloted from 2011 - 2012 and evaluated in 2014
  - Considered successful
- More popular with the public, policy makers, and beneficiares. 

---

# What Have Others Done?

HIP is the only means-tested financial incentives program. DUFB has yet to be evaluated in a grocery-store environment.

- The incentive, a 30% rebate, is very different from the DUFB incentive
- Had enough problems that more research is warrented
  - Survey recall
  - Confusion, lack of understanding of how the incentive worked
  - Major retailer in county opted out of HIP

--

# What Am I Doing?

Analyzing transaction data from a single supermarket chain that has piloted and expanded the DUFB program from 2 stores, to 5, to 17 stores, starting in 2014.

Unlike HIP, expansion and store-selection was *non-random*. I consider this a mixed blessing.

---

# How Am I Doing the Analysis?

### Data

- All sales data from 32 stores (17 treated, 15 control) from 2014-2016
- **Status**: Being transferred. 

